### ISSUE TITLE
data limits?

### ISSUE THREAD

**Issue by shubbey** [thorben-frank/mlff#5]
Hello,
I was able to get my data loaded from a .npz file but the program is hanging and locking up my box just after the data is loaded.  I suspect it is running out of RAM (I have 32GB).  My dataset has approx 1M molecules and the .npz file size is about 4GB.  I have trained the same dataset using SpookyNet (which is how I was led to this),  but since that operates at a lower level (where I wrote all of the training code), it was easier to inspect.  I'm not at that stage yet here and am only using train_so3krates directly.  From your experience should I be able to load this dataset on my machine?  Besides the 32GB of RAM I also have an RTX 4090 with 24GB.  I am happy to rent a more powerful machine to test this out but I would like to get an idea of the resource usage.  Thanks for any help!

**Comment by thorben-frank** [comment]
Hey, 
I did training on an A100 with 40GB RAM on datasets that have more than 3M molecules, so I would expect that this should work. 
How many atoms has the smallest/largest molecule in your dataset? And have you created the .npz file yourself or did you create it from an ASE file using the method provided by mlff? Maybe you could create a dataset which only has e.g. 2000 structures from the big dataset to check if the problem is still appearing. That might give a hint if it is really due to the size of the data set. 
Best,
Thorben

**Comment by shubbey** [comment]
Hi Thorben,
The largest molecule is 68 atoms.   I created the npz myself.  I will run some tests to see where it's going wrong, but since it crashed the machine I'm guessing it ran out of memory.

Unrelated: how does one resume the training from a saved checkpoint?  I will dig into the code but this wasn't obvious to me from the documentation.  

Thanks!

**Comment by shubbey** [comment]
I was able to get this working on a smaller set.  I'll keep pushing the limits to figure out where  the issue is.  I have some unrelated questions that I hope you can assist with:
1) What is the metric being used for the reported (in wandb) validation E / training E?  Is this the average error per molecule or per atom in the molecule?  Is it an rmse, mse, or something else?  As an example, I currently am seeing a validation E of ~0.019 eV which I would consider exceptionally good for this model at this stage if it refers to, eg rmse of the avg molecule.

2) When running 'evaluate' we are seeing rmse/mse/R2.  Again I wonder what this is relative to the reported validation E etc. My numbers here are MUCH worse:
Metrics on the test data split:
{'R2': {'E': 0.9713376372454778, 'F': 0.9831101349354341},
 'mae': {'E': 0.872336035586654, 'F': 0.029479420427149527},
 'rmse': {'E': 0.8962344504077089, 'F': 0.04926944062204484}}

My splits for this run are 100k/20k/2k train/valid/test.  In my other models (eg SpookyNet), validation and test have closely matched as I would expect.  So I'm assuming I'm looking at different measures here.  However, and rmse of 0.89 eV is quite a bit worse than what I've obtained for those models.  It may be legit as this is a substantially smaller dataset and I've only trained for a few hours.  At the very least I suspect I'm misunderstanding what the Training/Validation E/F is during training.

Thanks for any help you can give me!

**Comment by thorben-frank** [comment]
1. 68 atoms is indeed much larger than the largest structure I had in the data set I used when training on the 3M structure data set. Given your observation that it runs through with a smaller data set size, it seems to be a memory issue. 

2. Since you created the `.npz` file yourself, I have a few questions: How do you do padding on the atomic numbers and the forces?

3. Currently, there is no pre-implemented option to resume training from a checkpoint. From a high-level persepective, it could be done by initializing the [`flax.training.train_state`](https://flax.readthedocs.io/en/latest/_modules/flax/training/train_state.html) using the [`flax.training.checkpoint`](https://flax.readthedocs.io/en/latest/guides/use_checkpointing.html#id2) function. Afterwards, training could be run as if the parameters had been initialized randomly. However, when restarting training one has to be careful with the history of the optimizer (here Adam) since this might mess up training right after the restart. Note that `flax` is moving the `orbax` for checkpointing, such that the current checkpoint API will be depracted soon. When updating to `orbax`, I will add the option of resuming the training from checkpoint but for the soon to be depracted checkpoint API it does not make sense for me anymore. 

4. In wandb the mse loss per molecule (energy) and per component (forces) is reported. It is a bit surprising that your validation energy error is so much larger than the training error. A few questions that might help me to better understand what might be going on: For how many steps did you run the training when you evaluated the model? What is your trade-off parameter between energy and forces during training? Is the validation force error in line with what you observe during training? When you have structures of different compositions, does the training split contain all atomic numbers that are also in the test data? Do you shift/center the energies before training, e.g. by substracting the mean or an atom type specific shift?

**Comment by shubbey** [comment]
Regarding your questions:
2) I pad the extra columns in the npz file with 0s and pass in a node_mask.  Here is what I use to convert my data for use in .npz:
```
z = []
R = []
F = []
E = []
for td in tqdm(tds): # data in tds
    n = len(td.species)
    pad1D = [0]*(nmax-n)
    pad2D = [(0,0,0)]*(nmax-n)
    td.species.extend(pad1D)
    td.coords.extend(pad2D)
    td.forces.extend(pad2D)
    z.append(td.species)
    R.append(td.coords)
    F.append(td.forces)
    E.append(td.energy)
z = np.array(z)
R = np.array(R)
F = np.array(F)
E = np.array(E)
node_mask = np.where(z > 0, True, False)
np.savez("force.npz",z=z,R=R,F=F,E=E,node_mask=node_mask)
```

For energies, I have subtracted off the base atomic energies of the atoms in the molecule and converted to eV prior to saving here.

3) That would be great, thank you.  

4) My validation error and training error are similar and very good if it's reporting what I think.  Where I'm having trouble is in the evaluation stage, where I run this data against 2000 reserved molecules from the same set (of the 1.2M molecules, I am doing a 100k/20k/2k split (to fit in memory for now).  When I run the 'evaluation' command, I get this output:
```
Metrics on the test data split:
{'R2': {'E': 0.9748019048860834, 'F': 0.9900514739427135},
 'mae': {'E': 0.9177237828073489, 'F': 0.02278412459170981},
 'rmse': {'E': 0.9378109311902325, 'F': 0.037813241835393384}}
```
which is not on the same scale as the training/validation errors.  This data all comes from the same source so I'd expect validation and testing to be similar.  So I'm assuming I'm looking at different metrics.  For reference, I computed this just now, when the training is at approx 350k steps in.  Here is a training report:
https://api.wandb.ai/links/shubbey/sptyibbt

I am using all of the default parameters to train_so3krates.  So it is a 100:1 F:E ratio.  As noted, I am subtracting off base atomic energies.   This is all done in pre-processing before I hand off to the training.  I have not looked much at the forces but they also seem to be scaled differently in training/validation vs testing.  So I think the issue is in what is being reported.  Eg if the training data was reported as error per atom and the testing as error per molecule (although that doesn't fit either!).

All of the data should be from the same source (a random selection of molecules from my much larger set) but I should verify that.  I think if I take a median of the test error that should give an idea of outliers.

[Edit]  I ran a script to print out the individual errors for each molecule's energy in the test set (via predictions_on_test.npz) and they are consistent with my overall rmse there, ranging from about 0.7-1 eV.  By contrast, the errors in the validation set sent to wandb (Validation E) is around 0.01 eV-- two orders of magnitude smaller.  Surely this can't be correct so I must be misinterpreting what Validation E / Training E / etc mean.  But also an error of 1eV in the test set after this much training is extremely large so that doesn't seem correct to me either.   I will delve into writing my own training routine next, as that will give me a better sense of what I'm doing wrong here.  Any insight you can provide will be great!
 
Thanks again for the help!

**Comment by thorben-frank** [comment]
Sorry, I think my answer before was not clear enough regarding the reported errors during training. The training logs the MSE whereas the `evaluate` function returns the MAE, RMSE and R2 correlation coefficient. Thus, one should roughly get an RMSE from the `evaluate` function that corresponds to the square root of the force validation loss reported during training. In the link you send me, the force validation MSE is `MSE = 0.0021` such that one would expect an `RMSE = 0.0458` on the test set. I think this is in line with the reported `RMSE = 0.037`.

For the energy I agree, that the error is to large - given the error on the validation set. However, I think this is not an issue with the logging. 
Outliers might indeed be an option. Another option might be, that your test set has atomic types that are not in the training/validation set. This has happened to me before on the Qm7x dataset. Some atomic type (I fortgot which one exactly) is only present in very few structures. When sampling only a part from the whole data set, there is the chance that this atomic type is not included in the training/validation data set but is present in the test set. A similiar thing might happen for the structure sizes. Assuming the test data contains sizes that are not part of the training/validation data. This would make sense in the light of the observation that the force errors during validation seem to better match the final test error than the energies.

**Comment by shubbey** [comment]
Thanks for the clarification.  So I discovered a couple of things.

Running `evaluate --on valid` gives:
```
Metrics on the valid data split:
{'R2': {'E': 0.9746405204785697, 'F': 0.9870156237574393},
 'mae': {'E': 0.9108948466581084, 'F': 0.02132905029128276},
 'rmse': {'E': 0.9302927023865983, 'F': 0.042853426303138986}}
```

My Validation F from the wandb file is reported as: 
```
MSE (F) = 0.001838  or
RMSE (F)  = 0.0428 
```
which matches what we see above.  Success!

HOWEVER, if we look at Validation E, we get a different story.  In wandb, I have:
```
MSE (E) = 0.01015 or
RMSE (E) = 0.1007
```
which is not what we see in the evaluate (there we have 0.9302).

So I think we are looking at a different metric.  At first I thought that maybe the Validation E was reporting the scaled metric, since E is scaled down by 0.01.  However, that doesn't seem to be the case since the equation:
```
Validation loss = 0.01 * Validation E + 0.99 * Validation F
```
matches the reported numbers exactly.

I dug around the code to see if I could figure out what this metric is, but I couldn't see any other scaling factor.  I'm wondering if it is reporting an E-loss per atom, since that is how I do it in my SpookyNet program as recommended in the associated paper.  But I don't see where this would be setup in the code.

Can you provide some clarification here? Thanks!

**Comment by thorben-frank** [comment]
I tried to reproduce the issue by running training on a molecule from the MD17 data set and for me the reported MSE in wandb and the validation error from `evaluate --on valid` match for both, energy and forces. 

I also checked with a small QM7x test file (which differs in the structure sizes) and I still have matching MSE and RMSE predictions. 

When you plot the predicted energies vs the ground truth energies, how does this look like? You can do so, using the `predictions_on_valid.npz` file crreated by `evaluate --on valid` and the following code snippet
```
d = dict(np.load('/path/to/predictions_on_valid.npz', allow_pickle=True))
E_pred = d['predictions'].item()['E']
E_true = d['targets'].item()['E']

plt.scatter(E_true.reshape(-1), E_pred.reshape(-1))
```
And you are right, there is no additional scaling factor involved.

**Comment by shubbey** [comment]
![output](https://github.com/thorben-frank/mlff/assets/24950802/83768e15-b5db-4db1-b91a-598e6a73218b)
Which looks pretty good. However, if I print out the errors I can confirm that they are in the ~1.0 eV range as opposed to the reported ~0.1 ish range (once adjusted for MAE etc) in the training data for the Validation E:
```
for i in range(len(target_energies)):
   print(abs(target_energies[i]-predicted_energies[i]))
mae = np.abs(predicted_energies - target_energies).mean()
print(f'MAE: {mae:.4f} (eV)')
```
MAE: 0.9109 (eV)

**Comment by thorben-frank** [comment]
Could you maybe add a diagonal (E_true == E_model) line into the plot? From inspection by eyesight there seems to be an offset between the ground truth energies and the model energies.

**Comment by shubbey** [comment]
Interesting,  I think you are correct!
![output](https://github.com/thorben-frank/mlff/assets/24950802/51f65ef9-a5c4-41fb-a187-b43fc28d16c1)

If it's not obvious, maybe I can construct a small example of the data for you to try.

**Comment by thorben-frank** [comment]
My expectation would be, that correcting for an estimated shift will give an `RMSE` close to `sqrt(MSE)`. 

This would be great, since with the data I have everything seems to work as expected.

**Comment by shubbey** [comment]
Can you tell me where it may be adding in this shift?  My data is all preprocessed so the npz contains the shifted information, which is then run through the train and evaluate programs.  They seem to be interpreting it differently, or else I'm doing something wrong.

**Comment by shubbey** [comment]
I believe that the issue is here:
```
The energy scale of the data, tend to increase rapidly with the number of atoms in the system. 
However, relevant scale of energy changes is usually on the scale of a few eV, such that one typically 
shifts the energy by the mean of the energies in the --n_train training data points. This is done by 
default when running the train_so3krates command.
```

since I am passing in my data into the training with the default parameters, I believe it is adding in this shift prior to training but not in the evaluate program.  I'll do another training run with only the raw data.

**Comment by thorben-frank** [comment]
I think you are right, there is an issue with taking the mean when one has structures of different sizes in the data set. This is silently accepted by my dataset implementation although it actually should throw an error. 

The problem is actually here https://github.com/thorben-frank/mlff/blob/74f45676c8eedbda8c3c68b05c6edeb01d4118db/mlff/data/dataset.py#L314 where the per atom shift is calculated as the energy mean over the training data set divided by the number of atoms. However, the number of atoms is defined from the shape of the array that has the atomic types, which due to padding is not the real size of the structures.

The so calculated scales are saved to the `scales.json` file which is loaded during evaluation https://github.com/thorben-frank/mlff/blob/74f45676c8eedbda8c3c68b05c6edeb01d4118db/mlff/cAPI/mlff_eval.py#L126 and used to apply a per atom shift. For this reason it is not seen during training but during evaluation.

Since you have already scaled your data, I think the best way would be to simply disable the mean shift. I think this should be possible by e.g. passing `--shift_by no` to the `train_so3krates` command.

**Comment by shubbey** [comment]
Success!   Training without shifts now produces results consistent with the evaluate output.  Thank you.  I'll try to run a test with my full dataset to see how this compares with SpookyNet.  The preliminary analysis looks promising.
